# Generated by Django 2.1.1 on 2019-04-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20190403_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum'),
        ),
    ]
