# Generated by Django 2.2 on 2019-04-06 13:57

from django.db import migrations, models
import quotes.models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20190406_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='date',
        ),
        migrations.AddField(
            model_name='quote',
            name='year',
            field=models.IntegerField(blank=True, default=2019, null=True, validators=[quotes.models.validate_year], verbose_name='Datum'),
        ),
    ]
