# Generated by Django 2.2 on 2019-04-09 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20190409_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Quote', verbose_name='Zitat'),
        ),
    ]
