# Generated by Django 2.2 on 2019-04-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_auto_20190409_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
    ]
