# Generated by Django 2.2 on 2019-04-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_auto_20190415_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='likers',
        ),
        migrations.AddField(
            model_name='quote',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='sichtbar'),
        ),
    ]
